### ISSUE TITLE
DearEIS proble csv data importing

### ISSUE THREAD

**Issue by andremugen24** [vyrjana/DearEIS#14] opened 2023-10-26 09:03 UTC
Hi! 

I cannot open this csv file in DearEIS, even thought csv files are supported, any ideas?

![Screenshot 2023-10-26 175650](https://github.com/vyrjana/DearEIS/assets/136600574/0cf63c3e-397b-4bc4-a2c4-784b759e48e7)

[Potentiostatic EIS 1 (-0.150 V).csv](https://github.com/vyrjana/DearEIS/files/13175301/Potentiostatic.EIS.1.-0.150.V.csv)

Thanks in advance!
Andrea

**Comment by vyrjana** [comment] 2023-10-26 17:05
Hi!

The issue is due to the column headers in the data (see the paragraph below for a detailed explanation). For now you should be able to fix the issue by, e.g., removing the spaces in the column headers in your data files (i.e., "Z Real" -> "ZReal" and "Z Imag" -> "ZImag"). This issue will be fixed in an upcoming update, but I cannot provide an ETA for that at the moment.

The [relevant lines in pyimspec](https://github.com/vyrjana/pyimpspec/blob/8a0ee850c22456caedd5725ad7db91fb6ada28a0/src/pyimpspec/data/data_set.py#L688-L696) that define the substrings that are used to identify columns do not currently include "z real" and "z imag". This in combination with the "mag" substring in "Z Imag" causes the "Z Imag" column to be interpreted as the column for the magnitude/modulus of the impedance. However, in that case columns for the frequency data and the phase data are also expected. The error arises when the code checks to make sure that at least three columns (in this case frequency, magnitude, and phase) have been identified.

**Comment by andremugen** [comment] 2023-10-30 02:23
Thank you very much! Now works :)

**Closed** 2023-11-07 21:22 UTC
Labels: bug
